language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
before_install:
  - gem update bundler
script:
  - bundle exec rake test
notifications:
  webhooks:
    urls:
      - https://nulab-inc.com/hubot/travis?room=3741
    on_success: change
